config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "admin#index"
  get 'admin' => 'admin#index'
  get 'user/:id' => 'admin#user', as: 'user'
  get 'request_details/:id' => 'admin#request_details', as: 'request_details'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  post 'send_sos' => 'messages#send_sos'
  post 'send_test' => 'messages#send_test'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :request
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  scope :sos, -> { where(request_type: "sos") }
  scope :test, -> { where(request_type: "test") }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :requests
  has_many :messages, through: :requests

  MAX_TESTS_PER_DAY = 2
  MAX_SOS_PER_DAY = 3

  MAX_TESTS_PER_DAY_PREMIUM = 5
  MAX_SOS_PER_DAY_PREMIUM = 5

  def general_report
    puts "-------------------------"
    puts "-> Report for #{self.store_user_id} -> #{self.name}"
    puts "-> Requests: #{self.requests.count}"
    puts "-> Messages: #{self.messages.count}"
    puts "-------------------------"
  end

  def last_request_report
    puts "-------------------------"
    puts "-> Last request for #{self.store_user_id} -> #{self.name}"
    request = self.requests.last
    puts "-> Request ID: #{request.id}"
    puts "-> OS: #{request.os}"
    puts "-> Created at: #{request.created_at}"
    puts "-> Messages: #{request.messages.count}"
    puts "-> Messages list:"
    request.messages.each do |message|
      puts "  -> Message ID: #{message.id}"
      puts "  -> Message: #{message.message}"
      puts "  -> Message type: #{message.message_type}"
      puts "  -> Status: #{message.status}"
      puts "  -> Destination: #{message.destination}"
      puts "  -> Name: #{message.name}"
      puts "  -> Created at: #{message.created_at}"
      puts "  <<-----------------------"
    end
    puts "-------------------------"
  end

  # If the user is premium, use the premium limits
  # If it is a test, use the test limits
  def can_send_messages_today?(is_test)
    if is_test
      return self.requests_today.test.count < self.max_tests_per_day
    else
      return self.requests_today.sos.count < self.max_sos_per_day
    end
  end

  def max_tests_per_day
    self.is_premium ? MAX_TESTS_PER_DAY_PREMIUM : MAX_TESTS_PER_DAY
  end

  def max_sos_per_day
    self.is_premium ? MAX_SOS_PER_DAY_PREMIUM : MAX_SOS_PER_DAY
  end

  def requests_today
    return self.requests.where("created_at >= ?", Time.zone.now.beginning_of_day)
  end

  def clear_requests_today
    self.requests_today.destroy_all
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def index
    @requests = Request.all.order(created_at: :desc)
  end

  def user
    @user = User.find(params[:id])
  end

  def request_details
    @request = Request.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :check_api_key

  # POST /send_sos
  # {
  #   os: 'ios',
  #   user_id: '1',
  #   user_name: 'John Doe',
  #   contacts: [
  #     {name: 'John Doe', phone: '123-456-7890', email: 'john@doe.com'},
  #     {name: 'Jane Doe', phone: '123-456-7890', email: 'jane@doe.com'}
  #   ]
  # }
  def send_sos
    request = Messages::SendSos.call(params)
    render json: request[:response], status: request[:status]
  end

  # POST /send_test
  # {
  #   os: 'ios',
  #   user_id: '1',
  #   user_name: 'John Doe',
  #   contacts: [
  #     {name: 'John Doe', phone: '123-456-7890', email: 'john@doe.com'},
  #   ]
  # }
  def send_test
    request = Messages::SendTest.call(params)
    render json: request[:response], status: request[:status]
  end

  private
  def check_api_key
    if request.headers['Authorization'] != ENV['API_KEY_HEADER']
      puts "API KEY: #{request.headers['Authorization']}"
      puts "ENV API KEY: #{ENV['API_KEY_HEADER']}"
      render json: {message: 'No estas autorizado para realizar esta acción'}, status: 403
      return
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Administrador Boton de pánico</h1>
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Fecha</th>
            <th>SO</th>
            <th>Tipo</th>
            <th>Mensajes</th>
          </tr>
        </thead>
        <tbody> 
          <% @requests.each do |log| %>
            <tr>
              <td><%= link_to log.user.store_user_id, user_path(log.user_id), class: 'btn btn-success' %></td>
              <td><%= log.user.name %></td>
              <td><%= log.created_at %></td>
              <td><%= log.os %></td>
              <td><%= log.request_type %></td>
              <td><%= link_to log.messages.count, request_details_path(log.id), class: 'btn btn-primary btn-xs' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/request_details.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Detalles de solicitud</h1>
      <%= link_to "Regresar", admin_path, class: 'btn btn-primary' %>
      <table class="table">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Destino</th>
            <th>Tipo</th>
            <th>Mensaje</th>
            <th>Respuesta</th>
          </tr>
        </thead>
        <tbody>
          <% @request.messages.each do |message| %>
            <tr>
              <td><%= message.created_at %></td>
              <td><%= message.destination %></td>
              <td><%= message.message_type %></td>
              <td><%= message.message %></td>
              <td><%= message.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/user.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Detalles del usuario</h1>
      <%= link_to "Regresar", admin_path, class: 'btn btn-primary' %>
      <table class="table">
        <tbody>
          <tr>
            <td>ID</td>
            <td><%= @user.store_user_id %></td>
          </tr>
          <tr>
            <td>Nombre</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>Fecha de creación</td>
            <td><%= @user.created_at %></td>
          </tr>
          <tr>
            <td>Premium</td>
            <td><%= @user.is_premium %></td>
          </tr>
        </tbody>
      </table>
      <h2> Historial de solicitudes </h2>
      <table class="table">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>SO</th>
            <th>Tipo</th>
            <th>Mensajes</th>
          </tr>
        </thead>
        <tbody>
          <% @user.requests.each do |log| %>
            <tr>
              <td><%= log.created_at %></td>
              <td><%= log.os %></td>
              <td><%= log.request_type %></td>
              <td><%= link_to log.messages.count, request_details_path(log.id), class: 'btn btn-primary btn-xs' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PanicBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <div class="container">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
          <span class="fs-4">Aplicación de botón de pánico</span>
        </a>

        <% if admin_signed_in? %>
          <ul class="nav nav-pills">
            <li class="nav-item"><a href="/" class="nav-link active" aria-current="page">Home</a></li>
            <li class="nav-item">
              <%= button_to( "Log Out", destroy_admin_session_path, method: :delete, class: 'btn btn-danger') %>
            </li>
          </ul>
        <% end %>
      </header>
      <%= yield %>
    </div>
    
    
  </body>
</html>